### ISSUE TITLE
GitHub Integration - API Implementation

### ISSUE THREAD

**Issue by LouisIV** [Hackerstat/website#7] opened 2020-08-15 04:43 UTC
- [x] Get GitHub API key
- [x] Determine required routes
- [x] Get User's contributions to create a contribution graph

#### Contribution Graph

[User](https://docs.github.com/en/graphql/reference/objects#user)

- [Contributions](https://docs.github.com/en/graphql/reference/objects#contributionscollection)

  - [Calendar](https://docs.github.com/en/graphql/reference/objects#contributioncalendar)

**Comment by Cgunter1** [comment] 2021-07-07 17:57
# Changes
This issue is a duplicate of #9. Look over there for more info of why this issue is closed.

**Closed by Cgunter1** 2021-07-07 17:57 UTC
Labels: Integration
